server:
  servlet:
    encoding:
      charset: utf-8
      enabled: true
      force: true
  port: 8080

spring:
  jpa:
    hibernate:
      ddl-auto: create
    generate-ddl: true
    show-sql: true

  datasource:
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  redis:
    port: ${REDIS_PORT}
    host: ${REDIS_HOST}

jwt:
  header: ${HEADER}
  prefix: ${PREFIX}
  secret: ${SECRET}
  exp:
    access: ${ACCESS}
    refresh: ${REFRESH}