server:
  servlet:
    encoding:
      charset: utf-8
      enabled: true
      force: true
  port: 8080

spring:
  jpa:
    hibernate:
      ddl-auto: update
    generate-ddl: true
    show-sql: true

  datasource:
    url: jdbc:mysql://gominbbushe.cqglzcfmqaha.ap-northeast-2.rds.amazonaws.com:3306/gominbreak?serverTimezone=UTC&characterEncoding=UTF-8
    username: root
    password: rhqmffls13!
    driver-class-name: com.mysql.cj.jdbc.Driver

  redis:
    port: 6379
    host: localhost

jwt:
  header: Authorization
  prefix: Bearer
  secret: 6rOg66+867+M7IWU
  exp:
    access: 1800000
    refresh: 604800000